---@class Palette
---@field bg string
---@field fg string
---@field selection string
---@field comment string
---@field red string
---@field orange string
---@field yellow string
---@field green string
---@field purple string
---@field cyan string
---@field pink string
---@field bright_red string
---@field bright_green string
---@field bright_yellow string
---@field bright_blue string
---@field bright_magenta string
---@field bright_cyan string
---@field bright_white string
---@field ansi_black string
---@field ansi_white string
---@field ansi_bright_black string
---@field white_bright string
---@field bg_dark string
---@field bg_darker string
---@field menu string
---@field visual string
---@field gutter_fg string
---@field nontext string
---@field white string
---@field black string
return {
   bg = "#282A36",
   fg = "#F8F8F2",
   selection = "#44475A",
   comment = "#6272A4",
   red = "#FF5555",
   orange = "#FFB86C",
   yellow = "#F1FA8C",
   green = "#50FA7B",
   purple = "#BD93F9",
   cyan = "#8BE9FD",
   pink = "#FF79C6",
   bright_red = "#FF6E6E",
   bright_green = "#69FF94",
   bright_yellow = "#FFFFA5",
   bright_blue = "#D6ACFF",
   bright_magenta = "#FF92DF",
   bright_cyan = "#A4FFFF",
   bright_white = "#FFFFFF",
   ansi_black = "#21222C",
   ansi_white = "#F8F8F2",
   ansi_bright_black = "#6272A4",
   white_bright = "#FFFFFF",
   bg_dark = "#21222C",
   bg_darker = "#191A21",
   menu = "#21222C",
   visual = "#44475A",
   gutter_fg = "#6272A4",
   nontext = "#3E404A",
   white = "#ABB2BF",
   black = "#191A21",
}
